Event manager
wozane/education pull request #1
Opened 2017-05-31 13:08 UTC by wozane

2017-06-05 08:57 UTC, esse requested changes
Some changes required, however - overall: good code 👍

2017-06-05 08:57 UTC, esse commented on event_manager/lib/validate_phone_number.rb
> +    return 'Invalid phone format' unless number.is_a?(String)
I believe in this approach it we would be better to raise an exception instead

2017-06-05 08:57 UTC, esse commented on event_manager/lib/validate_phone_number.rb
> +        'Invalid phone number'
Same here - exception would be better

2017-06-05 08:57 UTC, esse commented on event_manager/lib/validate_phone_number.rb
>    def call(number)
I would rather use method name `validate` and class method, i.e. `self.validate` name here.

2017-06-07 08:39 UTC, wozane commented
request for review before merge @esse

2017-06-07 08:58 UTC, esse approved these changes
👍

2017-06-07 09:16 UTC, closed without merging

2017-06-07 09:17 UTC, wozane commented
Branch merged manually